class Object:
    id: int
    x: int
    y: int
    horizontal_flip: int
    vertical_flip: int
    rotation: int
    trigger_red: int
    trigger_green: int
    trigger_blue: int
    duration: int
    touch_triggered: int
    secret_coin_id: int
    portal_checked: int
    tint_ground: int
    player_color_1: int
    player_color_2: int
    blending: int
    color_channel_id_1pt9: int
    editor_layer_1: int
    color: int
    color_2: int
    target_color: int
    z_layer: int
    z_order: int
    move_x: int
    move_y: int
    easing: int
    text: int
    scale: int
    group_parent: int
    opacity: int
    active_trigger: int
    hsv_enabled: int
    color_2_hsv_enabled: int
    hsv: int
    color_2_hsv: int
    fade_in: int
    hold: int
    fade_out: int
    pulse_hsv: int
    copied_color_hsv: int
    copied_color_id: int
    target: int
    target_type: int
    yellow_teleportation_portal_distance: int
    activate_group: int
    groups: int
    lock_to_player_x: int
    lock_to_player_y: int
    copy_opacity: int
    editor_layer_2: int
    spawn_triggered: int
    spawn_duration: int
    dont_fade: int
    main_only: int
    detail_only: int
    dont_enter: int
    rotate_degrees: int
    times_360: int
    lock_object_rotation: int
    target_pos: int
    x_mod: int
    y_mod: int
    strength: int
    animation_id: int
    count: int
    subtract_count: int
    pickup_mode: int
    item_id: int
    hold_mode: int
    toggle_mode: int
    interval: int
    easing_rate: int
    exclusive: int
    multi_trigger: int
    comparison: int
    dual_mode: int
    speed: int
    delay: int
    y_offset: int
    activate_on_exit: int
    dynamic_block: int
    block_b: int
    glow_disabled: int
    rotation_speed: int
    disable_rotation: int
    orb_multi_activate: int
    use_target: int
    target_pos_axes: int
    editor_disable: int
    high_detail: int
    count_multi_activate: int
    max_speed: int
    randomize_start: int
    animation_speed: int
    linked_group: int
    camera_zoom: int
    free_mode: int
    edit_free_cam_settings: int
    free_cam_easing: int
    free_cam_padding: int
    ord: int
    no_effects: int
    reversed: int
    song_start: int
    time_mod: int
    no_touch: int
    animate_on_trigger: int
    scale_x: int
    scale_y: int
    perspective_x: int
    perspective_y: int
    only_move: int
    passable: int
    hide: int
    nonstick_x: int
    ice_block: int
    player_1: int
    override_count: int
    follow_camera_x: int
    follow_camera_y: int
    follow_camera_x_mod: int
    follow_camera_y_mod: int
    particle_setup: int
    use_obj_color: int
    gravity: int
    scale_x_by: int
    scale_y_by: int
    group_probabilities: int
    div_by_x: int
    div_by_y: int
    streak_additive: int
    unlink_dual_gravity: int
    hide_ground: int
    hide_p1: int
    hide_p2: int
    camera_edge: int
    keep_velocity: int
    change_channel: int
    grip_slope: int
    hide_mg: int
    player_only: int
    disable_controls_p1: int
    player_2: int
    _pt: int
    gradient_layer: int
    gradient_bl: int
    gradient_br: int
    gradient_tl: int
    gradient_tr: int
    gradient_vertex_mode: int
    gradient_disable: int
    gradient_id: int
    quick_start: int
    follow_group: int
    follow_easing: int
    follow_p1: int
    follow_p2: int
    aream_move_dist: int
    area_offset: int
    area_length: int
    effect_id: int
    area_move_angle: int
    area_scale_x: int
    area_scale_y: int
    area_move_x: int
    area_move_y: int
    area_xy_mode: int
    area_easing: int
    area_direction: int
    mod_front: int
    mod_back: int
    parent_groups: int
    area_inwards: int
    area_parent: int
    deadzone: int
    area_mirrored: int
    nonstick_y: int
    effect_priority: int
    enter_channel: int
    scale_stick: int
    disable_grid_snap: int
    no_audio_scale: int
    follow_mode: int
    center_group_id: int
    target_move_distance: int
    rotation_dynamic: int
    rotation_target: int
    rotation_offset: int
    events: int
    sequence: int
    seq_mode: int
    seq_min_int: int
    seq_reset: int
    seq_reset_type: int
    spawn_ordered: int
    spawn_remap: int
    material: int
    pickup_mod: int
    preview_opacity: int
    timer_display: int
    timer_start: int
    no_timer_override: int
    ignore_time_warp: int
    timer_mod: int
    timer_paused: int
    timer_control: int
    timer_target: int
    timer_stop: int
    timer_multi_active: int
    item_type_1: int
    item_type_2: int
    item_type_3: int
    num_mod: int
    num_op_1: int
    num_op_2: int
    num_op_3: int
    num_mod_2: int
    num_offset: int
    round_op_1: int
    round_op_2: int
    set_persistent: int
    pers_target_all: int
    pers_reset: int
    pers_timer: int
    extra_sticky: int
    dont_boost_y: int
    seq_unique_remap: int
    no_particle: int
    gradient_disable_all: int
    dont_boost_x: int
    extended_collision: int
    event_target: int
    control_id: int
    use_control_id: int
    dont_edit_area_parent: int
    neg_op_1: int
    neg_op_2: int
    stop_mode: int